version: 2
updates:
- package-ecosystem: "bundler"
  directory: "/"
  schedule:
    interval: "daily"
  target-branch: "master"
- package-ecosystem: "gomod"
  directory: "/src/rabbitmq-smoke-tests/"
  vendor: true
  schedule:
    interval: "daily"
  target-branch: "master"
- package-ecosystem: "gitsubmodule"
  directory: "/"
  schedule:
    interval: "daily"
  target-branch: "master"
