version: 2
updates:
- package-ecosystem: "bundler"
  directory: "/"
  target-branch: "main"
  schedule:
    interval: "daily"
- package-ecosystem: "gomod"
  directory: "/src/rabbitmq-smoke-tests/"
  schedule:
    interval: "daily"
  target-branch: "main"
- package-ecosystem: "gitsubmodule"
  directory: "/"
  schedule:
    interval: "daily"
  target-branch: "main"
